"""Core product, industry and visual-direction catalogs."""

from __future__ import annotations

from typing import Any

from .ui_intelligence_models import (
    DesignReference,
    FrameworkPlaybook,
)


class UIIntelligenceFoundationCatalogMixin:
    FRONTEND_ALIASES = {
        "next": "react",
        "nextjs": "react",
        "nuxt": "vue",
        "nuxtjs": "vue",
        "expo": "react-native",
        "react-native": "react-native",
        "flutter": "flutter",
        "swiftui": "swiftui",
        "taro": "miniapp",
        "uniapp": "miniapp",
        "uni-app": "miniapp",
        "wechat-miniprogram": "miniapp",
        "miniprogram": "miniapp",
        "miniapp": "miniapp",
        "mp-weixin": "miniapp",
        "weapp": "miniapp",
        "electron": "desktop",
        "tauri": "desktop",
        "wails": "desktop",
        "ionic": "hybrid-mobile",
        "capacitor": "hybrid-mobile",
        "desktop": "desktop",
    }

    DESIGN_REFERENCES: tuple[DesignReference, ...] = (
        DesignReference(
            slug="linear.app",
            name="Linear",
            rationale="适合作为高密度工作台、issue/workflow、专业工程产品的精度参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/linear.app",
            direction="dark-mode-native precision with compressed typography",
            signals=[
                "近黑底色上的层级化亮度控制",
                "克制的品牌紫/靛色只用于关键交互",
                "高信息密度下仍然可扫描的面板和工作区",
            ],
            cautions=[
                "不要复制它的聊天式外壳",
                "不要把极暗界面套到不适合的行业场景",
            ],
            fit_product_types=("saas", "dashboard"),
            fit_industries=("general", "fintech", "developer"),
            fit_styles=("professional", "minimal", "modern"),
            fit_frontends=("react", "vue", "desktop"),
            priority=10,
        ),
        DesignReference(
            slug="vercel",
            name="Vercel",
            rationale="适合作为开发者品牌官网、产品营销页和黑白极简技术品牌的叙事参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/vercel",
            direction="minimal monochrome marketing with engineered typography",
            signals=[
                "极简黑白体系与大留白",
                "压缩标题字距与工程感文案节奏",
                "用工作流图和产品截图解释价值",
            ],
            cautions=[
                "不要把它做成空洞的白板官网",
                "不要只学黑白配色而丢掉品牌辨识度",
            ],
            fit_product_types=("landing", "saas"),
            fit_industries=("general", "developer"),
            fit_styles=("minimal", "professional", "modern"),
            fit_frontends=("react", "vue", "web"),
            priority=9,
        ),
        DesignReference(
            slug="stripe",
            name="Stripe",
            rationale="适合作为金融、支付、平台型产品的可信商业表达参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/stripe",
            direction="editorial gradients with trustworthy infrastructure polish",
            signals=[
                "大标题与柔和渐变形成品牌识别",
                "信息层级清晰，信任模块丰富",
                "复杂能力通过内容编排降低理解成本",
            ],
            cautions=[
                "不要滥用紫色渐变",
                "不要只复制视觉，不补齐支付/安全信任模块",
            ],
            fit_product_types=("landing", "saas"),
            fit_industries=("fintech", "general"),
            fit_styles=("luxury", "professional", "modern"),
            fit_frontends=("react", "web"),
            priority=9,
        ),
        DesignReference(
            slug="raycast",
            name="Raycast",
            rationale="适合作为桌面效率工具、命令中心和操作导向产品的紧凑交互参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/raycast",
            direction="compact utility-first dark chrome with vivid accents",
            signals=[
                "高效的紧凑布局与快捷动作",
                "工具型品牌感而非后台感",
                "深色界面上的高识别度重点色",
            ],
            cautions=[
                "不要把桌面壳层直接搬到普通 Web SaaS",
                "不要牺牲可读性去追求过度紧凑",
            ],
            fit_product_types=("dashboard", "saas"),
            fit_industries=("general", "developer"),
            fit_styles=("modern", "professional"),
            fit_frontends=("desktop", "react"),
            priority=8,
        ),
        DesignReference(
            slug="notion",
            name="Notion",
            rationale="适合作为内容、知识、协作型产品的信息组织与柔和编辑体验参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/notion",
            direction="warm editorial minimalism with content-first hierarchy",
            signals=[
                "内容优先的阅读层级",
                "柔和中性色与少量强调色",
                "块级结构清晰，适合知识产品",
            ],
            cautions=[
                "不要把内容产品做成死板文档页",
                "不要在高操作密度后台里硬套这种轻质感",
            ],
            fit_product_types=("content", "saas"),
            fit_industries=("education", "general"),
            fit_styles=("minimal", "modern"),
            fit_frontends=("react", "vue", "web"),
            priority=8,
        ),
        DesignReference(
            slug="figma",
            name="Figma",
            rationale="适合作为设计协作、创意工具和多功能产品的高活力品牌表达参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/figma",
            direction="playful professional color energy with tool-centric clarity",
            signals=[
                "强品牌配色但不牺牲可用性",
                "创意工具感而不是营销模板感",
                "通过色块和图形语言建立识别度",
            ],
            cautions=[
                "不要把多彩系统做成廉价插画风",
                "不要忽略业务界面的秩序和层级",
            ],
            fit_product_types=("landing", "saas"),
            fit_industries=("general", "education"),
            fit_styles=("playful", "modern"),
            fit_frontends=("react", "web"),
            priority=7,
        ),
        DesignReference(
            slug="intercom",
            name="Intercom",
            rationale="适合作为服务型 SaaS、客户支持和沟通场景的信任与亲和力参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/intercom",
            direction="friendly operational SaaS with service-oriented clarity",
            signals=[
                "亲和但不幼稚的服务体验",
                "帮助/对话模块与产品主线并存",
                "品牌色与业务效率平衡",
            ],
            cautions=[
                "不要演变成聊天壳层产品",
                "不要把所有流程都塞进对话窗口",
            ],
            fit_product_types=("saas", "landing"),
            fit_industries=("general", "education", "healthcare"),
            fit_styles=("professional", "playful", "modern"),
            fit_frontends=("react", "web"),
            priority=7,
        ),
        DesignReference(
            slug="supabase",
            name="Supabase",
            rationale="适合作为开发者产品、数据库/平台型工具的技术品牌表达参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/supabase",
            direction="developer dark system with emerald technical accent",
            signals=[
                "暗色开发者语境 + 绿色品牌点缀",
                "技术内容与产品价值并行",
                "截图、代码和配置说明并重",
            ],
            cautions=[
                "不要直接复制绿色黑底组合",
                "不要失去行业特定的信任表达",
            ],
            fit_product_types=("saas", "dashboard", "landing"),
            fit_industries=("developer", "general"),
            fit_styles=("professional", "modern"),
            fit_frontends=("react", "web"),
            priority=7,
        ),
        DesignReference(
            slug="airbnb",
            name="Airbnb",
            rationale="适合作为消费服务、生活方式与强图像叙事产品的体验参考。",
            source="https://github.com/VoltAgent/awesome-design-md/tree/main/design-md/airbnb",
            direction="warm hospitality marketplace with rounded trustful surfaces",
            signals=[
                "摄影/图像驱动的转化叙事",
                "圆角与暖色调带来的友好感",
                "场景化内容与决策辅助并存",
            ],
            cautions=[
                "不要把服务平台做成纯广告册",
                "不要忽略高频任务路径和结构清晰度",
            ],
            fit_product_types=("ecommerce", "landing"),
            fit_industries=("general", "beauty", "education"),
            fit_styles=("playful", "luxury", "modern"),
            fit_frontends=("react", "web"),
            priority=6,
        ),
    )

    FRAMEWORK_PLAYBOOKS: dict[str, FrameworkPlaybook] = {
        "uni-app": FrameworkPlaybook(
            framework="uni-app",
            focus="多端业务应用的一套代码多端落地，但必须显式处理平台差异、导航、登录支付与包体性能。",
            rationale="适合微信/支付宝/抖音小程序、H5 与 App 共用业务模型，但不能把 Web 习惯直接平移到小程序与 App。",
            source_basis=[
                "本地 uniapp-dev-guide 的平台差异、custom navigation、login/payment/share 工程实践",
                "uni-app 官方关于 CSS/自定义导航/平台差异的约束模型",
            ],
            implementation_modules=[
                "自定义导航栏高度、状态栏占位、胶囊按钮区域必须独立建模",
                "登录/支付/分享流程按平台 provider 拆分，不做一套 UI 直接复用",
                "请求、存储、路由、权限、分包与条件编译要进入实现清单",
                "表单、列表、支付确认、状态页优先贴合小程序生态组件和交互节奏",
            ],
            platform_constraints=[
                "小程序与 App 不可依赖 DOM/window/localStorage/cookie 语义",
                "CSS 本地背景图、通配符选择器、复杂伪元素与 viewport 单位存在平台限制",
                "自定义导航启用后必须显式处理 status bar 与安全区",
                "支付、登录、手机号、分享链路必须按 provider 单独验收",
            ],
            execution_guardrails=[
                "先冻结 pages.json / 分包 / navigationStyle / provider 配置，再开始页面实现",
                "把触控热区、滚动性能、包体体积、图片体积和网络并发纳入 UI 约束",
                "预览与交付必须至少覆盖 H5、微信小程序、目标 App 三端差异说明",
            ],
            anti_patterns=[
                "把 Web 版 header、hover、复杂阴影和大 Hero 原样搬进小程序",
                "未区分 provider 就统一实现登录/支付/分享按钮和回调",
                "忽略 renderjs/WXS/nvue 差异后再用补丁修崩平台",
            ],
            native_capabilities=[
                "登录 provider（微信/支付宝/App）",
                "支付 provider、手机号授权、分享链路",
                "状态栏/安全区/胶囊按钮信息",
            ],
            validation_surfaces=[
                "H5 页面骨架与首屏性能",
                "微信小程序导航/支付/触控与包体策略",
                "目标 App 的原生导航、权限与支付回调",
            ],
            delivery_evidence=[
                "三端差异说明与条件编译点清单",
                "provider 配置、pages.json、分包与导航策略截图/说明",
            ],
        ),
        "taro": FrameworkPlaybook(
            framework="Taro",
            focus="React 技术栈驱动的小程序/多端业务应用，强调组件抽象与平台 API 包装。",
            rationale="适合团队已有 React/React Query/Tailwind 体系，但必须对齐小程序生态和包体限制。",
            source_basis=[
                "小程序生态组件与路由/权限约束",
                "跨端 React 组件复用与平台 API 包装经验",
            ],
            implementation_modules=[
                "平台 API 通过 hooks/service 封装，避免页面直调",
                "小程序列表、表单、支付路径优先选择生态组件而非 Web 组件硬适配",
                "分包、图片体积、请求并发和状态同步作为默认约束",
            ],
            platform_constraints=[
                "小程序端不可靠 hover 和复杂 DOM 结构表达交互",
                "路由层级、包体、网络并发、原生层级组件需单独处理",
            ],
            execution_guardrails=[
                "先冻结跨端组件边界，再决定哪些页面保留平台差异化",
                "用条件编译/运行时分支隔离支付、登录、地图、分享等能力",
            ],
            anti_patterns=[
                "把普通 React Web 页面直接搬进小程序容器",
                "组件设计不考虑包体与首屏性能",
            ],
            native_capabilities=[
                "小程序 API hooks/service 封装",
                "支付、登录、地图、分享 provider 分层",
            ],
            validation_surfaces=[
                "目标小程序端真实导航/包体/性能验证",
                "H5 回退策略与平台差异说明",
            ],
            delivery_evidence=[
                "跨端 service 封装说明",
                "小程序限制与降级清单",
            ],
        ),
        "react-native": FrameworkPlaybook(
            framework="React Native",
            focus="移动端原生交互优先，Web 设计语言只能作为品牌层，不能覆盖导航、手势和系统反馈。",
            rationale="适合需要复用 TS/React 能力的多端 App，但必须严格遵守移动端信息密度和触控范式。",
            source_basis=[
                "原生导航、手势、权限与离线缓存最佳实践",
            ],
            implementation_modules=[
                "导航、手势、表单、权限、离线缓存单独建模",
                "状态页、空态、错误态、权限拒绝态按移动端任务流设计",
                "推送、深链、文件上传、系统分享和生物识别作为平台能力面单独设计",
            ],
            platform_constraints=[
                "避免使用 Web 栅格、悬浮面板和 hover 交互作为核心模式",
                "iOS/Android 的安全区、返回手势、权限授权与通知策略需分开验收",
            ],
            execution_guardrails=[
                "优先原生反馈节奏和触控热区，再叠加品牌 token",
                "先冻结 navigation tree、权限矩阵与离线缓存策略，再做视觉抛光",
            ],
            anti_patterns=[
                "把 Web Dashboard 压缩到手机上",
                "只做通用页面，不定义 iOS/Android 差异化手势和系统入口",
            ],
            native_capabilities=[
                "push notification、deep link、share sheet、camera/media、biometric auth",
                "offline cache、background sync、permissions",
            ],
            validation_surfaces=[
                "iOS 真机/模拟器安全区、返回手势、分享与权限流",
                "Android 返回键、通知、文件权限与深链流",
            ],
            delivery_evidence=[
                "navigation tree 与权限矩阵",
                "离线/弱网/权限拒绝状态截图或验证记录",
            ],
        ),
        "flutter": FrameworkPlaybook(
            framework="Flutter",
            focus="高一致性跨端渲染与复杂动效，但必须避免 Material 默认味道直接上线。",
            rationale="适合品牌要求强、动效复杂的跨端 App，但主题和组件状态要先冻结。",
            source_basis=[
                "Flutter theme、Material/Cupertino 双栈约束",
            ],
            implementation_modules=[
                "主题色、字号、圆角、阴影和组件状态要先生成主题层",
                "导航、底栏、表单、空态、权限流程按移动端任务流落地",
                "深色模式、响应式断点、动画规范和平台感知组件策略前置冻结",
            ],
            platform_constraints=[
                "默认 Material 3 视觉不能直接作为商业 UI 成品",
                "iOS / Android / 桌面 targets 不能共用一套默认 Scaffold 语义直接上线",
            ],
            execution_guardrails=[
                "先定义 ThemeData / token 映射，再进入页面实现",
                "明确哪些页面需要 Cupertino/平台感知组件，而不是统一 Material 皮肤",
            ],
            anti_patterns=[
                "Material 默认控件直出",
                "只改颜色不改 typography、shape、elevation 和状态层级",
            ],
            native_capabilities=[
                "theme / localization / deep link / notification / app lifecycle",
            ],
            validation_surfaces=[
                "Android 与 iOS 的导航、手势、状态栏与 dark mode 一致性",
                "复杂动画页面的性能与掉帧验证",
            ],
            delivery_evidence=[
                "ThemeData/token 映射文档",
                "暗色模式与平台感知组件差异截图",
            ],
        ),
        "desktop": FrameworkPlaybook(
            framework="Desktop Web Shell",
            focus="桌面工作台要突出窗口范式、快捷键、菜单、离线、本地文件能力，而不是网页放大版。",
            rationale="适合 Electron/Tauri/Wails 等桌面壳，但必须显式设计本地能力、窗口层级和多面板结构。",
            source_basis=[
                "桌面效率工具与数据分析客户端的窗口/快捷键模式",
            ],
            implementation_modules=[
                "窗口状态、命令面板、侧栏/面板布局、本地文件与通知能力要进入骨架设计",
                "离线态、同步态、后台任务态必须是默认状态矩阵的一部分",
                "菜单栏、托盘、拖拽导入、文件关联、全局快捷键要有明确边界",
            ],
            platform_constraints=[
                "不能只做网页式顶部导航 + 单列内容区",
                "macOS / Windows 的菜单、标题栏、快捷键与窗口行为不能强行统一",
            ],
            execution_guardrails=[
                "先冻结快捷键、菜单栏、拖拽、文件读写与离线缓存交互",
                "明确哪些功能需要原生桥接，哪些继续留在 Web 层",
            ],
            anti_patterns=[
                "把 marketing website 套进桌面壳",
                "只有浏览器式 header/nav，没有 split view、command bar、local state",
            ],
            native_capabilities=[
                "filesystem、native notifications、tray/menu、window controls、offline cache",
            ],
            validation_surfaces=[
                "窗口布局、快捷键、文件导入导出、离线恢复",
                "macOS / Windows 标题栏和菜单行为差异",
            ],
            delivery_evidence=[
                "快捷键清单、窗口布局说明、原生桥接清单",
                "文件流与离线恢复验证结果",
            ],
        ),
    }

    ART_DIRECTION_LIBRARY: tuple[dict[str, Any], ...] = (
        {
            "id": "editorial-swiss",
            "name": "Editorial Swiss",
            "philosophy": "用排版、网格和留白建立权威感，而不是依赖炫技特效制造高级感。",
            "hero_treatment": "超大标题 + 精准副标题 + 一条强证据栏，首屏信息少但判断力强。",
            "narrative_mode": "先观点、后证据、再能力模块的编辑式叙事。",
            "visual_tension": "高对比字重、克制色彩、结构化留白。",
            "density_tempo": "spacious-to-compressed，首屏大留白，随后进入高密度证明区。",
            "proof_strategy": "用截图、数据、案例和注释替代装饰性图形。",
            "palette_strategy": "黑白/象牙白基底 + 一个品牌强调色。",
            "fit_product_types": ("landing", "saas", "content"),
            "fit_styles": ("minimal", "professional", "modern"),
            "fit_industries": ("general", "fintech", "legal", "developer"),
            "anti_cliches": [
                "不要堆彩色渐变球和玻璃拟态卡片",
                "不要把首屏做成只有一句 slogan 的空洞海报",
                "不要把营销页面做成聊天壳层",
            ],
            "tweak_axes": ["标题张力", "留白比例", "证据栏密度", "强调色强度"],
            "source_basis": ["Pentagram", "Information Architects", "Vercel"],
        },
        {
            "id": "precision-workspace",
            "name": "Precision Workspace",
            "philosophy": "把界面当成工作台，不把后台包装成营销页；信息必须服务任务完成。",
            "hero_treatment": "弱 Hero、强工作区预览，先展示主要操作面和状态面。",
            "narrative_mode": "以任务流和状态反馈驱动，而不是大段品牌叙事。",
            "visual_tension": "压缩排版、清晰分区、少量高识别度重点色。",
            "density_tempo": "compact-and-layered，高密度但保持扫描效率。",
            "proof_strategy": "用表格、状态矩阵、时间线和审计信号证明成熟度。",
            "palette_strategy": "近黑/冷灰基底 + 单一技术强调色。",
            "fit_product_types": ("dashboard", "saas", "content"),
            "fit_styles": ("professional", "modern", "minimal"),
            "fit_industries": ("general", "fintech", "developer"),
            "anti_cliches": [
                "不要把工作台拉成大 Hero + 卡片墙",
                "不要牺牲操作路径去换取装饰性大图",
                "不要使用空洞的发光科幻 UI",
            ],
            "tweak_axes": ["信息密度", "侧栏权重", "证据强度", "重点色面积"],
            "source_basis": ["Linear", "Raycast", "Supabase"],
        },
        {
            "id": "warm-trust",
            "name": "Warm Trust",
            "philosophy": "用亲和而克制的品牌语言建立信任，让专业感和温度同时存在。",
            "hero_treatment": "温暖背景 + 清晰价值陈述 + 近景产品/服务证明。",
            "narrative_mode": "先建立安全感，再逐步展开服务流程和结果承诺。",
            "visual_tension": "柔和色块、明确层级、图片与文字配合。",
            "density_tempo": "balanced，阅读舒适但关键信息就近出现。",
            "proof_strategy": "案例、评价、资质、流程说明和 FAQ 同时出现。",
            "palette_strategy": "暖中性色 + 可信主色 + 低饱和强调。",
            "fit_product_types": ("landing", "ecommerce", "content", "saas"),
            "fit_styles": ("professional", "playful", "luxury", "modern"),
            "fit_industries": ("healthcare", "beauty", "education", "general"),
            "anti_cliches": [
                "不要用廉价插画或库存图假装温度",
                "不要为了亲和力牺牲专业排版",
                "不要把信任模块放到页面尾部才出现",
            ],
            "tweak_axes": ["暖度", "图像比重", "评价/资质权重", "CTA 语气"],
            "source_basis": ["Intercom", "Airbnb", "Stripe"],
        },
        {
            "id": "cinematic-product",
            "name": "Cinematic Product",
            "philosophy": "用强叙事和高质感动态节奏表达产品势能，但不掉进赛博俗套。",
            "hero_treatment": "大场景首屏 + 产品视觉主物 + 明确行动入口。",
            "narrative_mode": "章节式推进，从氛围建立过渡到功能证明与结果展示。",
            "visual_tension": "深色背景、明确高光、强对比构图。",
            "density_tempo": "wide-to-focused，先铺开氛围，再收紧到产品证明。",
            "proof_strategy": "用场景截图、功能特写和节奏化模块替代空洞特效。",
            "palette_strategy": "深背景 + 控制数量的高亮 accent，不走霓虹紫粉。",
            "fit_product_types": ("landing", "saas"),
            "fit_styles": ("modern", "luxury", "playful"),
            "fit_industries": ("general", "developer", "beauty"),
            "anti_cliches": [
                "不要用紫粉赛博霓虹和电路板意象代表 AI",
                "不要让粒子和发光抢走内容主线",
                "不要缺少真实产品界面证据",
            ],
            "tweak_axes": ["氛围强度", "截图权重", "模块节奏", "对比度"],
            "source_basis": ["Locomotive", "Field.io", "Active Theory"],
        },
        {
            "id": "quiet-luxury",
            "name": "Quiet Luxury",
            "philosophy": "高级感来自秩序、材质和节奏，而不是堆砌昂贵视觉元素。",
            "hero_treatment": "精炼标题 + 精确文案 + 极少但高质量的视觉材料。",
            "narrative_mode": "少量高价值模块，强调品牌判断力和信任门槛。",
            "visual_tension": "细边框、深浅材质对比、克制动效。",
            "density_tempo": "spacious-and-deliberate，节奏慢但每块内容都很重。",
            "proof_strategy": "用案例、规格、服务细节和材料语言证明价值。",
            "palette_strategy": "高对比中性色 + 铜色/琥珀/深绿等受控强调。",
            "fit_product_types": ("landing", "content", "ecommerce"),
            "fit_styles": ("luxury", "minimal", "professional"),
            "fit_industries": ("beauty", "legal", "general"),
            "anti_cliches": [
                "不要把高级感误解成全黑+金色描边",
                "不要为了奢华感堆满玻璃反射和复杂纹理",
                "不要牺牲可读性和转化路径",
            ],
            "tweak_axes": ["材质感", "留白程度", "高光色比重", "文案密度"],
            "source_basis": ["Kenya Hara", "Müller-Brockmann", "Stripe"],
        },
        {
            "id": "playful-modular",
            "name": "Playful Modular",
            "philosophy": "活力不等于幼稚，颜色和形状必须服务模块化信息组织。",
            "hero_treatment": "鲜明品牌入口 + 轻插图/图形点缀 + 清楚的功能分组。",
            "narrative_mode": "模块化分块叙事，让复杂产品保持轻快但不散。",
            "visual_tension": "活跃配色、明确网格、较圆润的组件节奏。",
            "density_tempo": "balanced-to-brisk，信息丰富但不沉重。",
            "proof_strategy": "用角色收益、场景模块和实际界面替代抽象插画。",
            "palette_strategy": "高识别主色 + 低噪辅助色 + 充足中性色缓冲。",
            "fit_product_types": ("landing", "saas", "content"),
            "fit_styles": ("playful", "modern"),
            "fit_industries": ("education", "general"),
            "anti_cliches": [
                "不要变成儿童化卡通 UI",
                "不要用过多颜色破坏层级",
                "不要只有图形感没有业务路径",
            ],
            "tweak_axes": ["色彩活跃度", "圆角语气", "插图占比", "模块密度"],
            "source_basis": ["Figma", "Resn", "Build"],
        },
    )

    PRODUCT_PROFILES: dict[str, dict[str, Any]] = {
        "landing": {
            "surface": "品牌表达 + 价值转化",
            "information_density": "medium",
            "experience_goals": [
                "首屏 5 秒内讲清楚产品价值、差异化和下一步 CTA",
                "用案例、数据、截图、流程示意降低陌生用户的不确定感",
                "页面节奏要强，模块职责清晰，滚动过程中持续推动转化",
            ],
            "page_blueprints": [
                {
                    "page": "首页 / Landing",
                    "sections": [
                        "Hero（价值主张 + 证据 + CTA）",
                        "客户/媒体/合作方信任区",
                        "关键能力模块",
                        "真实使用场景/流程拆解",
                        "案例 / 评价 / 数据证明",
                        "FAQ + 强 CTA + Footer",
                    ],
                    "focus": "建立价值认知、形成转化路径、压缩理解成本",
                },
                {
                    "page": "功能详情页",
                    "sections": [
                        "功能价值开场",
                        "界面截图/交互演示",
                        "适用角色/行业场景",
                        "常见问题与限制说明",
                    ],
                    "focus": "把抽象卖点翻译成具体业务收益",
                },
            ],
            "component_priorities": [
                "Hero / CTA / Social Proof / Pricing / FAQ / Integration Wall / Use-case Cards",
            ],
            "conversion_modules": [
                "首屏强 CTA",
                "案例与客户证明",
                "对比式卖点表达",
                "价格/试用/预约入口",
            ],
            "banned_patterns": [
                "空洞 Hero + 只有一句口号",
                "大面积无意义渐变和玻璃卡片堆砌",
                "没有真实截图或可信证据的营销页",
            ],
        },
        "saas": {
            "surface": "产品介绍 + 工作流演示",
            "information_density": "medium-high",
            "experience_goals": [
                "产品价值、工作流和角色收益要同时可见",
                "把复杂能力拆成清晰的功能模块与任务路径",
                "强调效率、协作、可追踪和商业可信度",
            ],
            "page_blueprints": [
                {
                    "page": "官网 / 产品页",
                    "sections": [
                        "Value Hero + Product Screenshot",
                        "Workflow Explanation",
                        "Role-based Benefits",
                        "Security / Compliance / Cases",
                        "Pricing / CTA / FAQ",
                    ],
                    "focus": "让潜在客户快速理解产品如何落地到团队协作",
                },
                {
                    "page": "应用工作台",
                    "sections": [
                        "Global Header + Command Bar",
                        "Primary Workspace",
                        "Context Sidebar / Inspector",
                        "Recent Activities / Audit / Tasks",
                    ],
                    "focus": "提升日常使用效率与状态可见性",
                },
            ],
            "component_priorities": [
                "Command Bar / Filter Bar / Tabs / Data Cards / Sheets / Activity Timeline / Empty States",
            ],
            "conversion_modules": [
                "产品截图/录屏",
                "角色场景示意",
                "安全与集成说明",
                "试用与预约 CTA",
            ],
            "banned_patterns": [
                "所有模块都像同一层级的卡片墙",
                "信息太空，不能体现软件成熟度",
                "没有截图、没有流程、没有角色收益",
            ],
        },
        "dashboard": {
            "surface": "高密度信息 + 高效率操作",
            "information_density": "high",
            "experience_goals": [
                "高频路径要比视觉装饰更优先",
                "筛选、排序、批量操作、状态反馈必须完整",
                "保证复杂界面仍然具备扫描效率和上下文感",
            ],
            "page_blueprints": [
                {
                    "page": "总览 / Dashboard",
                    "sections": [
                        "KPI Summary Strip",
                        "Filter / Segment Bar",
                        "Chart Grid",
                        "Priority Alerts / Exceptions",
                        "Recent Activity / Tasks",
                    ],
                    "focus": "一屏读懂状态、风险、优先级",
                },
                {
                    "page": "列表 / Table Workspace",
                    "sections": [
                        "Search + Filters + Saved Views",
                        "Dense Data Table",
                        "Bulk Actions",
                        "Detail Drawer / Side Panel",
                    ],
                    "focus": "支持连续操作，而不是看完再跳页",
                },
            ],
            "component_priorities": [
                "KPI Cards / Filters / Data Table / Detail Drawer / Audit Timeline / Status Badges / Bulk Actions",
            ],
            "conversion_modules": [
                "不适用营销转化模块，优先风险提示、最近活动、审计与效率入口",
            ],
            "banned_patterns": [
                "把后台做成营销页",
                "大量空白和 oversized hero 占据工作区",
                "只有图表没有操作路径",
            ],
        },
        "ecommerce": {
            "surface": "购买决策 + 转化推进",
            "information_density": "medium-high",
            "experience_goals": [
                "商品价值、价格、优惠、信任和下一步动作必须就近出现",
                "首要关注商品理解、下单流程和决策辅助",
                "高质量图片、评价、配送与售后信息不可缺失",
            ],
            "page_blueprints": [
                {
                    "page": "首页",
                    "sections": [
                        "Hero / Seasonal Campaign",
                        "Category Entry",
                        "Featured Products",
                        "Reviews / Trust / Guarantees",
                        "Promotional CTA",
                    ],
                    "focus": "引导发现与快速进入购买路径",
                },
                {
                    "page": "商品详情",
                    "sections": [
                        "Gallery + Sticky Summary",
                        "Price / Variant / CTA",
                        "Shipping / Return / Trust",
                        "Review / FAQ / Recommendations",
                    ],
                    "focus": "减少决策犹豫并推进下单",
                },
            ],
            "component_priorities": [
                "Product Gallery / Sticky Summary / Review Cards / Recommendation Rails / Checkout Steps",
            ],
            "conversion_modules": [
                "评价与销量证据",
                "物流与售后承诺",
                "优惠信息与库存提示",
                "支付安全与退换政策",
            ],
            "banned_patterns": [
                "商品详情缺少图片、评价、规格和配送说明",
                "价格和 CTA 被分散到多个区域",
                "复杂花哨但不利于下单的动画",
            ],
        },
        "content": {
            "surface": "阅读效率 + 内容发现",
            "information_density": "medium",
            "experience_goals": [
                "阅读体验和内容结构优先于装饰",
                "列表、目录、相关推荐与订阅/分享路径要自然",
                "排版、字重、段落节奏要有明确的编辑感",
            ],
            "page_blueprints": [
                {
                    "page": "内容首页",
                    "sections": [
                        "Featured Story",
                        "Category Navigation",
                        "Content Feed",
                        "Author / Topic Modules",
                    ],
                    "focus": "建立内容层级与发现效率",
                },
                {
                    "page": "内容详情",
                    "sections": [
                        "Headline / Metadata",
                        "Table of Contents",
                        "Article Body",
                        "Related Content / Subscribe CTA",
                    ],
                    "focus": "高质量阅读与次级转化",
                },
            ],
            "component_priorities": [
                "Editorial Hero / Topic Filters / Table of Contents / Reading Progress / Author Cards",
            ],
            "conversion_modules": [
                "订阅 / 收藏 / 相关推荐 / 专题聚合",
            ],
            "banned_patterns": [
                "阅读页面被过多视觉噪音打断",
                "正文层级和留白失衡",
                "内容站首页像普通 SaaS 营销页",
            ],
        },
        "general": {
            "surface": "价值表达 + 核心流程可演示",
            "information_density": "medium",
            "experience_goals": [
                "先让用户看懂产品，再让用户完成第一步动作",
                "页面结构要能支持未来扩展，不做一次性展示壳子",
                "默认走现代商业产品基线，而不是试验性视觉",
            ],
            "page_blueprints": [
                {
                    "page": "首页",
                    "sections": [
                        "价值主张",
                        "核心功能",
                        "场景说明",
                        "信任证明",
                        "CTA",
                    ],
                    "focus": "建立理解和下一步动作",
                }
            ],
            "component_priorities": [
                "Cards / CTA / Social Proof / Feature Highlights / Empty States",
            ],
            "conversion_modules": [
                "价值说明 + 证据 + CTA",
            ],
            "banned_patterns": [
                "AI 模板式宣传页",
                "缺少信任元素和清晰 CTA",
                "视觉过度但功能主线不清楚",
            ],
        },
    }

    INDUSTRY_TRUST_RULES: dict[str, dict[str, Any]] = {
        "healthcare": {
            "trust_modules": [
                "医生/机构资质与执照信息",
                "预约、流程、费用边界说明",
                "隐私、数据安全和合规提示",
                "紧急/风险场景的可执行下一步",
            ],
            "tone": "专业、克制、低风险感、可读性优先",
            "banned_patterns": [
                "霓虹色和重动效",
                "夸张的 AI 科幻视觉",
                "低对比度和轻飘的卡片堆砌",
            ],
        },
        "fintech": {
            "trust_modules": [
                "费用、收益、风险说明",
                "安全、合规、权限与审计提示",
                "交易状态、到账时间和异常解释",
                "关键数字可追踪且具备来源说明",
            ],
            "tone": "可信、严谨、数字层级清晰、反馈即时",
            "banned_patterns": [
                "过度娱乐化视觉",
                "重要数字弱化或混乱",
                "没有安全与风控表达的金融界面",
            ],
        },
        "education": {
            "trust_modules": [
                "课程/能力路径",
                "阶段进度和成就反馈",
                "老师/机构背书",
                "试学、案例和成果展示",
            ],
            "tone": "清晰、友好、鼓励式反馈",
            "banned_patterns": [
                "术语堆叠、没有引导",
                "只讲功能，不讲学习路径",
            ],
        },
        "general": {
            "trust_modules": [
                "能力边界说明",
                "案例/截图/指标证明",
                "FAQ 与支持入口",
                "状态反馈和错误恢复路径",
            ],
            "tone": "现代、克制、有品牌感",
            "banned_patterns": [
                "只有概念没有证据",
                "所有页面都靠装饰性视觉撑场面",
            ],
        },
        "legal": {
            "trust_modules": [
                "律师资质与执照展示",
                "案件成功率与客户评价",
                "隐私保护与数据安全声明",
                "咨询流程与费用透明说明",
            ],
            "tone": "权威、严谨、专业、可信",
            "banned_patterns": [
                "过度活泼或娱乐化的视觉",
                "缺少资质证明的专业页面",
            ],
        },
        "beauty": {
            "trust_modules": [
                "技师资质与服务项目",
                "真实案例与效果对比",
                "预约流程与退改政策",
                "产品安全认证与成分说明",
            ],
            "tone": "精致、温暖、品牌感、女性友好",
            "banned_patterns": [
                "粗糙的排版和低质量图片",
                "缺少真人案例的纯装饰页面",
            ],
        },
        "restaurant": {
            "trust_modules": [
                "菜品实拍与价格展示",
                "营业时间与位置导航",
                "食品安全认证",
                "用户评价与推荐菜品",
            ],
            "tone": "温暖、食欲感、本地化、便捷",
            "banned_patterns": [
                "使用库存图片替代实际菜品",
                "菜单信息不完整或过时",
            ],
        },
        "travel": {
            "trust_modules": [
                "目的地实景图片与评价",
                "价格透明与退改政策",
                "安全提示与保险说明",
                "行程定制与客服支持",
            ],
            "tone": "向往感、安全感、便捷、值得信赖",
            "banned_patterns": [
                "过度修图导致期望落差",
                "隐藏费用和不透明的定价",
            ],
        },
        "real-estate": {
            "trust_modules": [
                "房源实景与户型图",
                "价格趋势与区域分析",
                "经纪人资质与评价",
                "交易流程与法律说明",
            ],
            "tone": "专业、值得信赖、数据驱动",
            "banned_patterns": [
                "过度美化的效果图替代实景",
                "关键信息（价格、面积）不突出",
            ],
        },
    }

    PRODUCT_COLOR_PALETTES: dict[str, dict[str, str]] = {
        # SaaS & Software
        "saas": {
            "primary": "#2563EB",
            "secondary": "#3B82F6",
            "accent": "#EA580C",
            "background": "#F8FAFC",
            "text": "#1E293B",
            "card": "#FFFFFF",
            "muted": "#E9EFF8",
            "border": "#E2E8F0",
            "name": "Trust Blue",
        },
        "micro-saas": {
            "primary": "#6366F1",
            "secondary": "#818CF8",
            "accent": "#059669",
            "background": "#F5F3FF",
            "text": "#1E1B4B",
            "card": "#FFFFFF",
            "muted": "#EBEFF9",
            "border": "#E0E7FF",
            "name": "Indigo Focus",
        },
        "b2b": {
            "primary": "#0F172A",
            "secondary": "#334155",
            "accent": "#0369A1",
            "background": "#F8FAFC",
            "text": "#020617",
            "card": "#FFFFFF",
            "muted": "#E8ECF1",
            "border": "#E2E8F0",
            "name": "Enterprise Navy",
        },
        "productivity": {
            "primary": "#0D9488",
            "secondary": "#14B8A6",
            "accent": "#EA580C",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F1F4",
            "border": "#99F6E4",
            "name": "Teal Efficiency",
        },
        "collaboration": {
            "primary": "#7C3AED",
            "secondary": "#8B5CF6",
            "accent": "#059669",
            "background": "#F5F3FF",
            "text": "#312E81",
            "card": "#FFFFFF",
            "muted": "#EBEFF9",
            "border": "#E0E7FF",
            "name": "Team Indigo",
        },
        "ai-platform": {
            "primary": "#A83AED",
            "secondary": "#A78BFA",
            "accent": "#0891B2",
            "background": "#FAF5FF",
            "text": "#1E1B4B",
            "card": "#FFFFFF",
            "muted": "#ECEEF9",
            "border": "#DDD6FE",
            "name": "AI Violet",
        },
        "design-tool": {
            "primary": "#4F46E5",
            "secondary": "#6366F1",
            "accent": "#EA580C",
            "background": "#EEF2FF",
            "text": "#312E81",
            "card": "#FFFFFF",
            "muted": "#EBEEF8",
            "border": "#C7D2FE",
            "name": "Creative Indigo",
        },
        "knowledge-base": {
            "primary": "#475569",
            "secondary": "#64748B",
            "accent": "#2563EB",
            "background": "#F8FAFC",
            "text": "#1E293B",
            "card": "#FFFFFF",
            "muted": "#EAEFF3",
            "border": "#E2E8F0",
            "name": "Slate Knowledge",
        },
        # E-commerce & Marketplace
        "ecommerce": {
            "primary": "#059669",
            "secondary": "#10B981",
            "accent": "#EA580C",
            "background": "#ECFDF5",
            "text": "#064E3B",
            "card": "#FFFFFF",
            "muted": "#E8F1F3",
            "border": "#A7F3D0",
            "name": "Commerce Green",
        },
        "ecommerce-luxury": {
            "primary": "#1C1917",
            "secondary": "#44403C",
            "accent": "#A16207",
            "background": "#FAFAF9",
            "text": "#0C0A09",
            "card": "#FFFFFF",
            "muted": "#E8ECF0",
            "border": "#D6D3D1",
            "name": "Luxury Noir",
        },
        "marketplace": {
            "primary": "#4F3AED",
            "secondary": "#A78BFA",
            "accent": "#16A34A",
            "background": "#FAF5FF",
            "text": "#4C1D95",
            "card": "#FFFFFF",
            "muted": "#ECEEF9",
            "border": "#DDD6FE",
            "name": "Market Purple",
        },
        "subscription-box": {
            "primary": "#D946EF",
            "secondary": "#E879F9",
            "accent": "#EA580C",
            "background": "#FDF4FF",
            "text": "#86198F",
            "card": "#FFFFFF",
            "muted": "#F0EEF9",
            "border": "#F5D0FE",
            "name": "Unbox Magenta",
        },
        # Finance & Fintech
        "fintech": {
            "primary": "#F59E0B",
            "secondary": "#FBBF24",
            "accent": "#8B5CF6",
            "background": "#0F172A",
            "text": "#F8FAFC",
            "card": "#222735",
            "muted": "#272F42",
            "border": "#334155",
            "name": "Crypto Gold",
        },
        "banking": {
            "primary": "#0E102A",
            "secondary": "#1E3A8A",
            "accent": "#A16207",
            "background": "#F8FAFC",
            "text": "#020617",
            "card": "#FFFFFF",
            "muted": "#E8ECF1",
            "border": "#E2E8F0",
            "name": "Bank Navy",
        },
        "insurance": {
            "primary": "#0369A1",
            "secondary": "#0EA5E9",
            "accent": "#16A34A",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E7EFF5",
            "border": "#BAE6FD",
            "name": "Trust Sky",
        },
        "financial-dashboard": {
            "primary": "#0E1D2A",
            "secondary": "#1E293B",
            "accent": "#22C55E",
            "background": "#020617",
            "text": "#F8FAFC",
            "card": "#0E1223",
            "muted": "#1A1E2F",
            "border": "#334155",
            "name": "Dark Finance",
        },
        "analytics": {
            "primary": "#1E40AF",
            "secondary": "#3B82F6",
            "accent": "#D97706",
            "background": "#F8FAFC",
            "text": "#1E3A8A",
            "card": "#FFFFFF",
            "muted": "#E9EEF6",
            "border": "#DBEAFE",
            "name": "Data Blue",
        },
        # Healthcare & Wellness
        "healthcare": {
            "primary": "#0891B2",
            "secondary": "#22D3EE",
            "accent": "#059669",
            "background": "#ECFEFF",
            "text": "#164E63",
            "card": "#FFFFFF",
            "muted": "#E8F1F6",
            "border": "#A5F3FC",
            "name": "Medical Cyan",
        },
        "mental-health": {
            "primary": "#8B5CF6",
            "secondary": "#C4B5FD",
            "accent": "#059669",
            "background": "#FAF5FF",
            "text": "#4C1D95",
            "card": "#FFFFFF",
            "muted": "#EDEFF9",
            "border": "#EDE9FE",
            "name": "Calm Violet",
        },
        "fitness": {
            "primary": "#F97316",
            "secondary": "#FB923C",
            "accent": "#22C55E",
            "background": "#1F2937",
            "text": "#F8FAFC",
            "card": "#313742",
            "muted": "#37414F",
            "border": "#374151",
            "name": "Energy Orange",
        },
        "beauty-spa": {
            "primary": "#EC4899",
            "secondary": "#F9A8D4",
            "accent": "#8B5CF6",
            "background": "#FDF2F8",
            "text": "#831843",
            "card": "#FFFFFF",
            "muted": "#F1EEF5",
            "border": "#FBCFE8",
            "name": "Blush Pink",
        },
        # Education & Learning
        "education": {
            "primary": "#4F46E5",
            "secondary": "#818CF8",
            "accent": "#EA580C",
            "background": "#EEF2FF",
            "text": "#1E1B4B",
            "card": "#FFFFFF",
            "muted": "#EBEEF8",
            "border": "#C7D2FE",
            "name": "Learn Indigo",
        },
        "e-learning": {
            "primary": "#0F766E",
            "secondary": "#14B8A6",
            "accent": "#EA580C",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F1F4",
            "border": "#5EEAD4",
            "name": "Edu Teal",
        },
        # Media & Entertainment
        "social-media": {
            "primary": "#E11D48",
            "secondary": "#FB7185",
            "accent": "#2563EB",
            "background": "#FFF1F2",
            "text": "#881337",
            "card": "#FFFFFF",
            "muted": "#F0ECF2",
            "border": "#FECDD3",
            "name": "Social Rose",
        },
        "gaming": {
            "primary": "#D53AED",
            "secondary": "#A78BFA",
            "accent": "#F43F5E",
            "background": "#0F0F23",
            "text": "#E2E8F0",
            "card": "#1E1C35",
            "muted": "#27273B",
            "border": "#4C1D95",
            "name": "Game Violet",
        },
        "music": {
            "primary": "#1E1B4B",
            "secondary": "#4338CA",
            "accent": "#22C55E",
            "background": "#0F0F23",
            "text": "#F8FAFC",
            "card": "#1B1B30",
            "muted": "#27273B",
            "border": "#312E81",
            "name": "Sound Dark",
        },
        "video-streaming": {
            "primary": "#0F0F23",
            "secondary": "#1E1B4B",
            "accent": "#E11D48",
            "background": "#000000",
            "text": "#F8FAFC",
            "card": "#0C0C0D",
            "muted": "#181818",
            "border": "#312E81",
            "name": "Stream Black",
        },
        "podcast": {
            "primary": "#1E1B4B",
            "secondary": "#312E81",
            "accent": "#F97316",
            "background": "#0F0F23",
            "text": "#F8FAFC",
            "card": "#1B1B30",
            "muted": "#27273B",
            "border": "#4338CA",
            "name": "Voice Dark",
        },
        "content": {
            "primary": "#475569",
            "secondary": "#94A3B8",
            "accent": "#2563EB",
            "background": "#FFFFFF",
            "text": "#1E293B",
            "card": "#F8FAFC",
            "muted": "#F1F5F9",
            "border": "#E2E8F0",
            "name": "Reader Slate",
        },
        "creative-agency": {
            "primary": "#EC4899",
            "secondary": "#F472B6",
            "accent": "#0891B2",
            "background": "#FDF2F8",
            "text": "#831843",
            "card": "#FFFFFF",
            "muted": "#F1EEF5",
            "border": "#FBCFE8",
            "name": "Agency Pink",
        },
        "creator-economy": {
            "primary": "#EC4899",
            "secondary": "#F472B6",
            "accent": "#EA580C",
            "background": "#FDF2F8",
            "text": "#831843",
            "card": "#FFFFFF",
            "muted": "#F1EEF5",
            "border": "#FBCFE8",
            "name": "Creator Pink",
        },
        # Professional Services
        "legal": {
            "primary": "#1E3A8A",
            "secondary": "#1E40AF",
            "accent": "#B45309",
            "background": "#F8FAFC",
            "text": "#0F172A",
            "card": "#FFFFFF",
            "muted": "#E9EEF5",
            "border": "#CBD5E1",
            "name": "Legal Blue",
        },
        "government": {
            "primary": "#140E2A",
            "secondary": "#334155",
            "accent": "#0369A1",
            "background": "#F8FAFC",
            "text": "#020617",
            "card": "#FFFFFF",
            "muted": "#E8ECF1",
            "border": "#E2E8F0",
            "name": "Gov Navy",
        },
        "nonprofit": {
            "primary": "#0891B2",
            "secondary": "#22D3EE",
            "accent": "#EA580C",
            "background": "#ECFEFF",
            "text": "#164E63",
            "card": "#FFFFFF",
            "muted": "#E8F1F6",
            "border": "#A5F3FC",
            "name": "Impact Cyan",
        },
        "consulting": {
            "primary": "#0E242A",
            "secondary": "#1E293B",
            "accent": "#2563EB",
            "background": "#F8FAFC",
            "text": "#020617",
            "card": "#FFFFFF",
            "muted": "#E8ECF1",
            "border": "#E2E8F0",
            "name": "Consult Navy",
        },
        # Real Estate & Hospitality
        "real-estate": {
            "primary": "#0F766E",
            "secondary": "#14B8A6",
            "accent": "#0369A1",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F0F3",
            "border": "#99F6E4",
            "name": "Property Teal",
        },
        "hotel": {
            "primary": "#1E3A8A",
            "secondary": "#3B82F6",
            "accent": "#A16207",
            "background": "#F8FAFC",
            "text": "#1E40AF",
            "card": "#FFFFFF",
            "muted": "#E9EEF5",
            "border": "#BFDBFE",
            "name": "Hotel Royal",
        },
        "travel": {
            "primary": "#0EA5E9",
            "secondary": "#38BDF8",
            "accent": "#EA580C",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E8F2F8",
            "border": "#BAE6FD",
            "name": "Travel Sky",
        },
        "restaurant": {
            "primary": "#DC2626",
            "secondary": "#F87171",
            "accent": "#A16207",
            "background": "#FEF2F2",
            "text": "#450A0A",
            "card": "#FFFFFF",
            "muted": "#F0EDF1",
            "border": "#FECACA",
            "name": "Dining Red",
        },
        # Technology & IOT
        "smart-home": {
            "primary": "#1E293B",
            "secondary": "#334155",
            "accent": "#22C55E",
            "background": "#0F172A",
            "text": "#F8FAFC",
            "card": "#1B2336",
            "muted": "#272F42",
            "border": "#475569",
            "name": "IoT Dark",
        },
        "ev-charging": {
            "primary": "#0891B2",
            "secondary": "#22D3EE",
            "accent": "#16A34A",
            "background": "#ECFEFF",
            "text": "#164E63",
            "card": "#FFFFFF",
            "muted": "#E8F1F6",
            "border": "#A5F3FC",
            "name": "EV Cyan",
        },
        "web3": {
            "primary": "#8B5CF6",
            "secondary": "#A78BFA",
            "accent": "#FBBF24",
            "background": "#0F0F23",
            "text": "#F8FAFC",
            "card": "#1E1D35",
            "muted": "#27273B",
            "border": "#4C1D95",
            "name": "Web3 Purple",
        },
        "logistics": {
            "primary": "#2563EB",
            "secondary": "#3B82F6",
            "accent": "#EA580C",
            "background": "#EFF6FF",
            "text": "#1E40AF",
            "card": "#FFFFFF",
            "muted": "#E9EFF8",
            "border": "#BFDBFE",
            "name": "Logistics Blue",
        },
        "agriculture": {
            "primary": "#15803D",
            "secondary": "#22C55E",
            "accent": "#A16207",
            "background": "#F0FDF4",
            "text": "#14532D",
            "card": "#FFFFFF",
            "muted": "#E8F0F1",
            "border": "#BBF7D0",
            "name": "Farm Green",
        },
        # Lifestyle & Events
        "dating": {
            "primary": "#E11D48",
            "secondary": "#FB7185",
            "accent": "#EA580C",
            "background": "#FFF1F2",
            "text": "#881337",
            "card": "#FFFFFF",
            "muted": "#F0ECF2",
            "border": "#FECDD3",
            "name": "Love Rose",
        },
        "wedding": {
            "primary": "#DB2777",
            "secondary": "#F472B6",
            "accent": "#A16207",
            "background": "#FDF2F8",
            "text": "#831843",
            "card": "#FFFFFF",
            "muted": "#F0EDF4",
            "border": "#FBCFE8",
            "name": "Wedding Fuchsia",
        },
        "pet-tech": {
            "primary": "#F97316",
            "secondary": "#FB923C",
            "accent": "#2563EB",
            "background": "#FFF7ED",
            "text": "#9A3412",
            "card": "#FFFFFF",
            "muted": "#F1F0F0",
            "border": "#FED7AA",
            "name": "Pet Orange",
        },
        # Portfolio & Personal
        "portfolio": {
            "primary": "#18181B",
            "secondary": "#3F3F46",
            "accent": "#2563EB",
            "background": "#FAFAFA",
            "text": "#09090B",
            "card": "#FFFFFF",
            "muted": "#E8ECF0",
            "border": "#E4E4E7",
            "name": "Mono Zinc",
        },
        "luxury-brand": {
            "primary": "#1C1917",
            "secondary": "#44403C",
            "accent": "#A16207",
            "background": "#FAFAF9",
            "text": "#0C0A09",
            "card": "#FFFFFF",
            "muted": "#E8ECF0",
            "border": "#D6D3D1",
            "name": "Luxury Stone",
        },
        # Job & HR
        "job-board": {
            "primary": "#0241A1",
            "secondary": "#0EA5E9",
            "accent": "#16A34A",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E7EFF5",
            "border": "#BAE6FD",
            "name": "Career Sky",
        },
        # Dashboard variants
        "dashboard": {
            "primary": "#1E40AF",
            "secondary": "#3B82F6",
            "accent": "#D97706",
            "background": "#F8FAFC",
            "text": "#1E3A8A",
            "card": "#FFFFFF",
            "muted": "#E9EEF6",
            "border": "#DBEAFE",
            "name": "Dashboard Blue",
        },
        "admin": {
            "primary": "#1B0E2A",
            "secondary": "#334155",
            "accent": "#2563EB",
            "background": "#F8FAFC",
            "text": "#020617",
            "card": "#FFFFFF",
            "muted": "#E8ECF1",
            "border": "#E2E8F0",
            "name": "Admin Slate",
        },
        # Landing & General
        "landing": {
            "primary": "#1D4ED8",
            "secondary": "#2563EB",
            "accent": "#EA580C",
            "background": "#FFFFFF",
            "text": "#111827",
            "card": "#F8FAFC",
            "muted": "#F1F5F9",
            "border": "#E5E7EB",
            "name": "Brand Blue",
        },
        "general": {
            "primary": "#3B82F6",
            "secondary": "#60A5FA",
            "accent": "#EA580C",
            "background": "#FFFFFF",
            "text": "#111827",
            "card": "#F8FAFC",
            "muted": "#F1F5F9",
            "border": "#E5E7EB",
            "name": "Professional Blue",
        },
        # Construction & Automotive
        "construction": {
            "primary": "#64748B",
            "secondary": "#94A3B8",
            "accent": "#EA580C",
            "background": "#F8FAFC",
            "text": "#334155",
            "card": "#FFFFFF",
            "muted": "#EBF0F5",
            "border": "#E2E8F0",
            "name": "Build Slate",
        },
        "automotive": {
            "primary": "#1E293B",
            "secondary": "#334155",
            "accent": "#DC2626",
            "background": "#F8FAFC",
            "text": "#0F172A",
            "card": "#FFFFFF",
            "muted": "#E9EDF1",
            "border": "#E2E8F0",
            "name": "Auto Dark",
        },
        # Photography & Creative
        "photography": {
            "primary": "#18181B",
            "secondary": "#27272A",
            "accent": "#F8FAFC",
            "background": "#000000",
            "text": "#FAFAFA",
            "card": "#0C0C0C",
            "muted": "#181818",
            "border": "#3F3F46",
            "name": "Photo Noir",
        },
        # Coworking & Services
        "coworking": {
            "primary": "#F59E0B",
            "secondary": "#FBBF24",
            "accent": "#2563EB",
            "background": "#FFFBEB",
            "text": "#78350F",
            "card": "#FFFFFF",
            "muted": "#F1F2EF",
            "border": "#FDE68A",
            "name": "Space Amber",
        },
        "home-services": {
            "primary": "#1E40AF",
            "secondary": "#3B82F6",
            "accent": "#EA580C",
            "background": "#EFF6FF",
            "text": "#1E3A8A",
            "card": "#FFFFFF",
            "muted": "#E9EEF6",
            "border": "#BFDBFE",
            "name": "Service Blue",
        },
        # Childcare & Senior Care
        "childcare": {
            "primary": "#F472B6",
            "secondary": "#FBCFE8",
            "accent": "#16A34A",
            "background": "#FDF2F8",
            "text": "#9D174D",
            "card": "#FFFFFF",
            "muted": "#F1F0F6",
            "border": "#FCE7F3",
            "name": "Care Pink",
        },
        "senior-care": {
            "primary": "#0290A1",
            "secondary": "#38BDF8",
            "accent": "#16A34A",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E7EFF5",
            "border": "#E0F2FE",
            "name": "Elder Sky",
        },
        # Medical & Health Services
        "medical-clinic": {
            "primary": "#0891B2",
            "secondary": "#22D3EE",
            "accent": "#16A34A",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F1F6",
            "border": "#CCFBF1",
            "name": "Clinic Teal",
        },
        "pharmacy": {
            "primary": "#15803D",
            "secondary": "#22C55E",
            "accent": "#0369A1",
            "background": "#F0FDF4",
            "text": "#14532D",
            "card": "#FFFFFF",
            "muted": "#E8F0F1",
            "border": "#BBF7D0",
            "name": "Pharma Green",
        },
        "dental": {
            "primary": "#0EA5E9",
            "secondary": "#38BDF8",
            "accent": "#059669",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E8F2F8",
            "border": "#BAE6FD",
            "name": "Dental Sky",
        },
        "veterinary": {
            "primary": "#115E59",
            "secondary": "#0D9488",
            "accent": "#EA580C",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F1F4",
            "border": "#99F6E4",
            "name": "Vet Teal",
        },
        # Food & Beverage
        "florist": {
            "primary": "#15803D",
            "secondary": "#22C55E",
            "accent": "#EC4899",
            "background": "#F0FDF4",
            "text": "#14532D",
            "card": "#FFFFFF",
            "muted": "#E8F0F1",
            "border": "#BBF7D0",
            "name": "Bloom Green",
        },
        "bakery-cafe": {
            "primary": "#92400E",
            "secondary": "#B45309",
            "accent": "#DC2626",
            "background": "#FEF3C7",
            "text": "#78350F",
            "card": "#FFFFFF",
            "muted": "#EDEEF0",
            "border": "#FDE68A",
            "name": "Bake Amber",
        },
        "brewery": {
            "primary": "#7C2D12",
            "secondary": "#B91C1C",
            "accent": "#A16207",
            "background": "#FEF2F2",
            "text": "#450A0A",
            "card": "#FFFFFF",
            "muted": "#ECEDF0",
            "border": "#FECACA",
            "name": "Brew Red",
        },
        # Transport & Media
        "airline": {
            "primary": "#1E3A8A",
            "secondary": "#3B82F6",
            "accent": "#EA580C",
            "background": "#EFF6FF",
            "text": "#1E40AF",
            "card": "#FFFFFF",
            "muted": "#E9EEF5",
            "border": "#BFDBFE",
            "name": "Sky Royal",
        },
        "news-media": {
            "primary": "#DC2626",
            "secondary": "#EF4444",
            "accent": "#1E40AF",
            "background": "#FEF2F2",
            "text": "#450A0A",
            "card": "#FFFFFF",
            "muted": "#F0EDF1",
            "border": "#FECACA",
            "name": "News Red",
        },
        "magazine": {
            "primary": "#18181B",
            "secondary": "#3F3F46",
            "accent": "#EC4899",
            "background": "#FAFAFA",
            "text": "#09090B",
            "card": "#FFFFFF",
            "muted": "#E8ECF0",
            "border": "#E4E4E7",
            "name": "Editorial Mono",
        },
        # Freelancer & Agency
        "freelancer": {
            "primary": "#4338CA",
            "secondary": "#6366F1",
            "accent": "#16A34A",
            "background": "#EEF2FF",
            "text": "#312E81",
            "card": "#FFFFFF",
            "muted": "#EBEFF9",
            "border": "#C7D2FE",
            "name": "Freelance Indigo",
        },
        "marketing-agency": {
            "primary": "#EC4899",
            "secondary": "#F472B6",
            "accent": "#0891B2",
            "background": "#FDF2F8",
            "text": "#831843",
            "card": "#FFFFFF",
            "muted": "#F1EEF5",
            "border": "#FBCFE8",
            "name": "Marketing Pink",
        },
        "event-management": {
            "primary": "#3A51ED",
            "secondary": "#A78BFA",
            "accent": "#EA580C",
            "background": "#FAF5FF",
            "text": "#4C1D95",
            "card": "#FFFFFF",
            "muted": "#ECEEF9",
            "border": "#DDD6FE",
            "name": "Event Purple",
        },
        # Community & Membership
        "membership": {
            "primary": "#ED3AD7",
            "secondary": "#A78BFA",
            "accent": "#16A34A",
            "background": "#FAF5FF",
            "text": "#4C1D95",
            "card": "#FFFFFF",
            "muted": "#ECEEF9",
            "border": "#DDD6FE",
            "name": "Community Purple",
        },
        "newsletter": {
            "primary": "#0219A1",
            "secondary": "#0EA5E9",
            "accent": "#EA580C",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E7EFF5",
            "border": "#BAE6FD",
            "name": "Newsletter Sky",
        },
        "digital-products": {
            "primary": "#4F46E5",
            "secondary": "#6366F1",
            "accent": "#16A34A",
            "background": "#EEF2FF",
            "text": "#312E81",
            "card": "#FFFFFF",
            "muted": "#EBEFF9",
            "border": "#C7D2FE",
            "name": "Digital Indigo",
        },
        "church": {
            "primary": "#ED3A51",
            "secondary": "#A78BFA",
            "accent": "#A16207",
            "background": "#FAF5FF",
            "text": "#4C1D95",
            "card": "#FFFFFF",
            "muted": "#ECEEF9",
            "border": "#DDD6FE",
            "name": "Faith Purple",
        },
        # Web3 & Digital
        "nft-web3": {
            "primary": "#8B5CF6",
            "secondary": "#A78BFA",
            "accent": "#FBBF24",
            "background": "#0F0F23",
            "text": "#F8FAFC",
            "card": "#1E1D35",
            "muted": "#27273B",
            "border": "#4C1D95",
            "name": "Web3 Violet",
        },
        "remote-work": {
            "primary": "#5B21B6",
            "secondary": "#7C3AED",
            "accent": "#059669",
            "background": "#F5F3FF",
            "text": "#312E81",
            "card": "#FFFFFF",
            "muted": "#EBEFF9",
            "border": "#E0E7FF",
            "name": "Remote Indigo",
        },
        # Streaming & Music
        "music-streaming": {
            "primary": "#1E1B4B",
            "secondary": "#4338CA",
            "accent": "#22C55E",
            "background": "#0F0F23",
            "text": "#F8FAFC",
            "card": "#1B1B30",
            "muted": "#27273B",
            "border": "#312E81",
            "name": "Sound Indigo",
        },
        # Recruitment & Local
        "recruitment": {
            "primary": "#02A18A",
            "secondary": "#0EA5E9",
            "accent": "#16A34A",
            "background": "#F0F9FF",
            "text": "#0C4A6E",
            "card": "#FFFFFF",
            "muted": "#E7EFF5",
            "border": "#BAE6FD",
            "name": "Career Sky",
        },
        "hyperlocal": {
            "primary": "#059669",
            "secondary": "#10B981",
            "accent": "#EA580C",
            "background": "#ECFDF5",
            "text": "#064E3B",
            "card": "#FFFFFF",
            "muted": "#E8F1F3",
            "border": "#A7F3D0",
            "name": "Local Green",
        },
        "online-course": {
            "primary": "#0D9488",
            "secondary": "#2DD4BF",
            "accent": "#EA580C",
            "background": "#F0FDFA",
            "text": "#134E4A",
            "card": "#FFFFFF",
            "muted": "#E8F1F4",
            "border": "#5EEAD4",
            "name": "Course Teal",
        },
    }
